version: "3"
services:
  web:
    build: # 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"

    environment:
      REDIS_HOST: redis-alpine
    volumes:
      - .:/code
  redis-alpine:
    image: "redis:alpine"