version: "3.9"
services:
  web:
    build: .
    ## image: emirozbir/redis-app:latest
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis-alpine
  redis-alpine:
    image: "redis:alpine"